### ISSUE TITLE
[Design]  이용권 메인 화면 개발

### ISSUE THREAD

**Issue by ows3090** [hobbyloop/hobbyloop-aos#41]
## 디자인 작업 내용
이용권 메인 UI 개발, API 연동은 추후 개발

## 관련 피그마 링크
https://www.figma.com/file/nYEBH6aqCI37ZX0X6w7Ena/%ED%95%98%EB%B9%84%EB%A3%A8%ED%94%84_Team-share?type=design&node-id=0-1&mode=design&t=Z0Wb6lfPaLnjsD6r-0

**Comment by ows3090** [comment]
@KamaTAEWOO @PARKJONGMlN 옛날에 생성한 이슈라 일단 종료하고 필요하면 새로운 이슈로 등록하겠습니다.

**Comment by KamaTAEWOO** [comment]
@ows3090 넵넵!
