### ISSUE TITLE
[Feature] DataStore PreferenceKey 하나의 파일로 관리

### ISSUE THREAD

**Issue by ows3090** [hobbyloop/hobbyloop-aos#72]
## 기능 개선 작업 내용
DataStore의 PreferenceKey로 현재 HOBBYLOOP_TOKEN, HOBBYLOOP_REFRESH_TOKEN 사용됨.
하지만 하나의 파일이 아닌 HobbyLoopInterceptor.kt와 SaveTokenInfoRepositoryImpl.kt 파일에서 하드코딩 형태로 사용

## 목적
Token을 사용하는 곳마다 Preference Key를 추가할 때 휴면에러 발생 가능성이 있으므로 하나의 파일로 관리하고 모듈을 import 하는 구조로 사용

**Comment by KamaTAEWOO** [comment]
@ows3090 원석님 이 부분은 data모듈에 repository가 있는데 network모듈에는 interceptor파일이 있습니다. 그런데 하나로 관리 하려면 data모듈에 있는 repository가 interceptor파일에 접근이 가능해야하는데 data모듈은 network모듈에 접근을  못하기 때문에 저번에 datastory를 주입하라고 지시하셨습니다.

**Comment by ows3090** [comment]
> @ows3090 원석님 이 부분은 data모듈에 repository가 있는데 network모듈에는 interceptor파일이 있습니다. 그런데 하나로 관리 하려면 data모듈에 있는 repository가 interceptor파일에 접근이 가능해야하는데 data모듈은 network모듈에 접근을  못하기 때문에 저번에 datastory를 주입하라고 지시하셨습니다. 

제가 말씀드린건 prefrenceKey만 따로 관리하라는거였어요~

**Comment by KamaTAEWOO** [comment]
> > @ows3090 원석님 이 부분은 data모듈에 repository가 있는데 network모듈에는 interceptor파일이 있습니다. 그런데 하나로 관리 하려면 data모듈에 있는 repository가 interceptor파일에 접근이 가능해야하는데 data모듈은 network모듈에 접근을  못하기 때문에 저번에 datastory를 주입하라고 지시하셨습니다.
> 
> 제가 말씀드린건 prefrenceKey만 따로 관리하라는거였어요~

그럼 object 파일을 하나 만들어서 거기에 키를 관리하여 import하여 사용할 수 있게 만들어 놓으면 될까요?

**Comment by ows3090** [comment]
> > > @ows3090 원석님 이 부분은 data모듈에 repository가 있는데 network모듈에는 interceptor파일이 있습니다. 그런데 하나로 관리 하려면 data모듈에 있는 repository가 interceptor파일에 접근이 가능해야하는데 data모듈은 network모듈에 접근을  못하기 때문에 저번에 datastory를 주입하라고 지시하셨습니다.
> > 
> > 
> > 제가 말씀드린건 prefrenceKey만 따로 관리하라는거였어요~
> 
> 그럼 object 파일을 하나 만들어서 거기에 키를 관리하여 import하여 사용할 수 있게 만들어 놓으면 될까요?

네네
