### ISSUE TITLE
[Feature] DataSource Remote, Local 폴더 및 네이밍 분리

### ISSUE THREAD

**Issue by ows3090** [hobbyloop/hobbyloop-aos#73]
## 기능 개선 작업 내용
TokenDataSource는 Local(DataStore)에서 가져오고 UserInfoDataSource는 Remote(Service)에서 데이터를 가져옴
파일 네이밍만 봐서 어디서 가져온지 알 수 없으므로 datasource 폴더 아래에 local, remote 생성 후 용도에 맞게 파일명 수정

## 목적
가독성 증가

**Comment by KamaTAEWOO** [comment]
@ows3090 원석님 TokenData도 처음에는 Service를 통해 받아와서 Datastore에 저장하여 사용하는건데 그래도 local에서 가져오는 걸로 하는 건지 궁금합니다. UserInfoDataSource는 remote인 거 확인했습니다.

**Comment by ows3090** [comment]
> @ows3090 원석님 TokenData도 처음에는 Service를 통해 받아와서 Datastore에 저장하여 사용하는건데 그래도 local에서 가져오는 걸로 하는 건지 궁금합니다. UserInfoDataSource는 remote인 거 확인했습니다.

DataSource는 그럼 local remote 각각 생성하셔야합니다

**Comment by KamaTAEWOO** [comment]
> > @ows3090 원석님 TokenData도 처음에는 Service를 통해 받아와서 Datastore에 저장하여 사용하는건데 그래도 local에서 가져오는 걸로 하는 건지 궁금합니다. UserInfoDataSource는 remote인 거 확인했습니다.
> 
> DataSource는 그럼 local remote 각각 생성하셔야합니다

네네! 확인했습니다.
